/* =============================================================================
 * 各购票平台「中文购买教程」
 *   difficulty: 1-5（对海外/中国用户的上手难度，越多★越难）
 *   每条包含：是否需注册、是否需要粉丝会员、证件要求、支付方式、步骤、贴士
 * ============================================================================= */
window.PLATFORM_GUIDES = {
  ticketmaster: {
    name: 'Ticketmaster（美国主力平台）',
    fanclubNeed: '视场次而定',
    difficulty: 3,
    region: '🇺🇸 美国',
    account: '需要注册 Ticketmaster 账号（邮箱即可，免费）',
    fanclub: '普通公售（General Sale）无需粉丝会员；但热门场次常先开「预售 Presale / Verified Fan」，需要预售码——预售码一般通过艺人官方 fandom（如 Weverse Membership）或注册 Verified Fan 获得。',
    idreq: '通常无需证件；电子票绑定在 Ticketmaster App，入场扫码即可',
    payment: '国际信用卡（Visa / Mastercard / Amex）',
    steps: [
      '提前用邮箱注册并登录 Ticketmaster 账号，绑定好支付方式',
      '想抢热门场：先关注艺人是否有 Verified Fan / 预售，去官方渠道领「预售码」',
      '开票前 10-15 分钟登录，进入等候室（Queue）排队',
      '轮到你后尽快选座、结算（有倒计时，动作要快）',
      '购票成功后票会出现在 Ticketmaster App 的「My Events」，入场出示二维码',
    ],
    tip: '开抢时不要反复刷新页面，会被踢到队尾；用手机 App + 网页双端待命更稳。',
  },
  axs: {
    name: 'AXS（美国，部分场馆/中小演出）',
    fanclubNeed: '视场次而定',
    difficulty: 3,
    region: '🇺🇸 美国',
    account: '需要注册 AXS 账号（邮箱注册）',
    fanclub: '多为公售；个别有预售码',
    idreq: '电子票为「AXS Mobile ID」，需在 AXS App 内查看，通常临近开演才可转移/显示',
    payment: '国际信用卡',
    steps: [
      '下载 AXS App 并注册登录',
      '找到对应场次，开票时进入排队页',
      '选票、用国际信用卡结算',
      '票在 App 的 AXS Mobile ID 中，入场扫码',
    ],
    tip: 'AXS 的电子票有时不能提前截图入场，务必装好 App 并登录本人账号。',
  },
  livenation: {
    name: 'Live Nation（美国，音乐节/演出主办）',
    fanclubNeed: '否',
    difficulty: 3,
    region: '🇺🇸 美国',
    account: '与 Ticketmaster 同属一家公司，购票多会跳转到 Ticketmaster 结算',
    fanclub: '音乐节一般公售；单场演出同 Ticketmaster 规则',
    idreq: '同 Ticketmaster',
    payment: '国际信用卡',
    steps: [
      '在 Live Nation 找到演出 / 音乐节',
      '点击购票，多数会跳转 Ticketmaster',
      '按 Ticketmaster 流程完成购买',
    ],
    tip: '账号可与 Ticketmaster 通用，提前注册好一个即可。',
  },
  nol: {
    name: 'NOL / Interpark Global（韩国，最友好海外版）',
    fanclubNeed: '视场次而定',
    difficulty: 2,
    region: '🇰🇷 韩国',
    account: '邮箱注册即可，有中文 / 英文 / 日文界面，专为海外用户设计（原 Interpark Global 升级而来）',
    fanclub: '普通预约无需会员；但部分热门演出有「粉丝俱乐部先行预售（fan-club presale）」，需先加入该团体的官方 fandom 才能参加先行场',
    idreq: '实名制演出现场需凭护照核验身份，购票时填写的英文名要与护照一致',
    payment: '国际信用卡（部分演出支持 PayPal）',
    steps: [
      '注册 NOL / Interpark Global 账号，切换到中文/英文',
      '完善本人信息（姓名需与护照一致）',
      '开票时进入演出页，选择场次与座位',
      '用国际信用卡付款',
      '按提示取电子票 / 现场凭护照换实体票',
    ],
    tip: '这是海外粉丝抢韩国场次的首选平台，界面最友好；热门团先看有没有 fan-club 先行。',
  },
  yes24: {
    name: 'YES24 Ticket（韩国，中小团 / 见面会主场）',
    fanclubNeed: '视场次而定',
    difficulty: 4,
    region: '🇰🇷 韩国',
    account: '需要注册账号，可用海外手机号收验证码（OTP）；有英文切换但更新略慢',
    fanclub: '很多演出设「粉丝俱乐部先行」，先行场需先加入对应 fandom；普通场为公售',
    idreq: '部分实名演出需现场核验证件',
    payment: '韩国本地银行卡更稳；国际信用卡有时受限，建议提前测试',
    steps: [
      '注册 YES24 账号，用海外手机号完成验证',
      '（如需）加入对应团体 fan-club 以参加先行预售',
      '开票时进入页面，通过安全字符验证后选座',
      '尽快付款（国际卡失败可尝试其它卡）',
    ],
    tip: '第四代/新人团、fanmeeting、大学庆典常在 YES24；建议提前备好可用的支付方式与海外手机号。',
  },
  melon: {
    name: 'Melon Ticket（韩国，对外国人最难）',
    fanclubNeed: '视场次而定',
    difficulty: 5,
    region: '🇰🇷 韩国',
    account: '需 Melon / Kakao 账号；界面基本仅韩文',
    fanclub: '常需 Melon 账号 + 粉丝俱乐部资格',
    idreq: '部分演出要求「韩国居民登记号（주민등록번호）」实名认证，外国人往往无法自行完成',
    payment: '多依赖韩国本地支付方式',
    steps: [
      '注册 Kakao / Melon 账号（韩文界面，可配合翻译）',
      '如演出要求韩国身份证号，外国人一般需要本地朋友协助或选择其它平台',
      '开票选座、用本地支付结算',
    ],
    tip: '对海外粉丝门槛最高。若同一场演出在 NOL / YES24 也有售，优先用那两个平台。',
  },
  weverse: {
    name: 'Weverse Shop（HYBE 系艺人，全球可用）',
    fanclubNeed: '是（先行预售需要）',
    difficulty: 2,
    region: '🌏 全球',
    account: '注册 Weverse 账号，多语言（含中文），全球粉丝友好',
    fanclub: '重点：HYBE 系艺人（BTS、SEVENTEEN、ENHYPEN、LE SSERAFIM、TXT、CORTIS 等）的预售通常需要「Weverse Membership（官方付费会员 / fandom）」。想抢先行场，请先购买对应艺人的 Weverse Membership。',
    idreq: '按各演出要求，通常电子票 / 会员绑定',
    payment: '国际信用卡',
    steps: [
      '注册 Weverse 账号并加入对应艺人社区',
      '若要抢先行/会员预售：先购买该艺人的 Weverse Membership',
      '开票时进入活动页，凭会员资格进入先行预售',
      '选票、用国际信用卡付款',
    ],
    tip: '抢 HYBE 艺人（如 BTS）几乎都要先有 Weverse Membership，务必提前开通。',
  },
  ticketlink: {
    name: 'TicketLink（韩国，部分演出 / 体育）',
    fanclubNeed: '视场次而定',
    difficulty: 4,
    region: '🇰🇷 韩国',
    account: '需注册账号，可用海外手机号验证；界面以韩文为主',
    fanclub: '部分演出有 fan-club 先行',
    idreq: '按演出要求',
    payment: '韩国本地卡更稳',
    steps: [
      '注册 TicketLink 账号并完成手机验证',
      '开票时进入页面选座',
      '用支持的支付方式付款',
    ],
    tip: '界面韩文较多，建议搭配浏览器翻译；能用 NOL 的场次优先用 NOL。',
  },
  pia: {
    name: 'Ticket Pia（日本最大票务平台之一）',
    fanclubNeed: '视场次而定',
    difficulty: 4,
    region: '🇯🇵 日本',
    account: '需注册 PIA 账号，支持英文邮箱注册；部分先行需加入 PIA Premium 会员',
    fanclub: '部分演出有抽选（抽票制），需加入先行会员或 fan-club',
    idreq: '日本境内演出通常需电子票绑定手机，实名入场',
    payment: '日本国内信用卡优先；部分支持海外卡（Visa/Master）',
    steps: [
      '注册 Ticket Pia 账号（https://t.pia.jp/）',
      '热门场次通常为抽选制：在指定时间内申请→抽选→中签后付款',
      '使用信用卡付款',
      '电子票通过 PIA App 或短信取票',
    ],
    tip: '日本热门 K-pop 演出基本是「抽选制」，不是先到先得；请关注抽选申请时间。',
  },
  lawson: {
    name: 'Lawson Ticket（日本便利店售票系统）',
    fanclubNeed: '视场次而定',
    difficulty: 4,
    region: '🇯🇵 日本',
    account: '注册 l-tike.com 账号（需日本手机号或海外邮箱）',
    fanclub: '常有先行抽选',
    idreq: '电子票或 Loppi 机取票（需在日本 Lawson 便利店）',
    payment: '信用卡或便利店付款',
    steps: [
      '注册 Lawson Ticket 账号',
      '参加抽选或一般发售',
      '中签 / 购票成功后付款',
      '取票方式：App 电子票或到 Lawson 便利店 Loppi 机器出票',
    ],
    tip: '如果人不在日本，取票方式可能受限；建议搭配代购服务或选择电子票场次。',
  },
  eplus: {
    name: 'e+ eplus（日本，电子票为主）',
    fanclubNeed: '视场次而定',
    difficulty: 3,
    region: '🇯🇵 日本',
    account: '注册 eplus 账号（邮箱即可）',
    fanclub: '部分有 eplus 会员先行',
    idreq: '电子票绑定 eplus App',
    payment: '信用卡（支持海外 Visa/Master）',
    steps: [
      '注册 eplus 账号（https://eplus.jp/）',
      '搜索演出，参加抽选或先着顺发售',
      '信用卡付款',
      '通过 eplus App 电子票入场',
    ],
    tip: '对海外粉丝相对友好；支持海外信用卡的比例较高。',
  },
  sistic: {
    name: 'SISTIC（新加坡官方票务平台）',
    fanclubNeed: '否',
    difficulty: 2,
    region: '🇸🇬 新加坡',
    account: '邮箱注册即可，有英文界面，非常友好',
    fanclub: '一般无需会员，公售为主',
    idreq: '电子票（e-ticket），入场扫二维码',
    payment: '国际信用卡（Visa / Mastercard / Amex）',
    steps: [
      '注册 SISTIC 账号（https://www.sistic.com.sg/）',
      '搜索演出，选择场次与座位',
      '用国际信用卡付款',
      '电子票发到邮箱，入场出示二维码',
    ],
    tip: '新加坡场次大多通过 SISTIC 售票，操作简单，对海外粉丝很友好。',
  },
  cityline: {
    name: 'Cityline（香港主要票务平台）',
    fanclubNeed: '否',
    difficulty: 3,
    region: '🇭🇰 香港',
    account: '注册 Cityline 账号（需香港手机号或邮箱）',
    fanclub: '一般公售；热门场次可能需 Cityline 会员优先购',
    idreq: '电子票或实体票（部分场馆支持到场取票）',
    payment: '信用卡（支持 Visa / Master / 银联）',
    steps: [
      '注册 Cityline 账号并验证',
      '开票时进入排队系统',
      '选座、用信用卡付款',
      '电子票或到指定地点取实体票',
    ],
    tip: '热门场次排队人数极多，建议提前登录、多设备待命。',
  },
  klook: {
    name: 'Klook（亚洲通用，特别适合海外粉丝）',
    fanclubNeed: '否',
    difficulty: 1,
    region: '🌏 亚洲多国',
    account: '邮箱注册，支持中文/英文/多语言',
    fanclub: '无需会员，公售为主',
    idreq: '电子凭证，通常无需证件',
    payment: '国际信用卡、PayPal、部分支持支付宝/微信',
    steps: [
      '注册 Klook 账号或直接购买',
      '搜索演出活动',
      '选择票档、付款',
      '电子凭证发送到邮箱 / App',
    ],
    tip: '最适合海外/中国粉丝的平台之一，支付方式多、界面友好；但不是所有场次都有。',
  },
  ticketmelon: {
    name: 'Ticketmelon（泰国主要票务平台）',
    fanclubNeed: '否',
    difficulty: 2,
    region: '🇹🇭 泰国',
    account: '邮箱注册，有英文界面',
    fanclub: '通常公售',
    idreq: '电子票，部分需出示护照',
    payment: '信用卡（支持国际卡）',
    steps: [
      '注册 Ticketmelon 账号',
      '搜索演出并选座',
      '用信用卡付款',
      '电子票在邮箱 / 账号中查看',
    ],
    tip: '泰国 K-pop 演出主要平台，英文界面对海外粉丝友好。',
  },
  smtickets: {
    name: 'SM Tickets（菲律宾主要票务平台）',
    fanclubNeed: '否',
    difficulty: 2,
    region: '🇵🇭 菲律宾',
    account: '邮箱注册即可',
    fanclub: '通常公售',
    idreq: '电子票或在 SM 商场取票',
    payment: '信用卡、GCash、部分支持 PayPal',
    steps: [
      '注册 SM Tickets 账号（https://smtickets.com/）',
      '找到演出页面选座',
      '信用卡或 GCash 付款',
      '电子票或到 SM 商场服务台取票',
    ],
    tip: '菲律宾场次主要通过此平台销售；如在当地可到任一 SM 商场取实体票。',
  },
  tixcraft: {
    name: '拓元 tixCraft（台湾主要票务平台）',
    fanclubNeed: '否',
    difficulty: 3,
    region: '🌏 台湾',
    account: '注册拓元账号（需手机号验证，支持国际号码）',
    fanclub: '部分场次有粉丝会员先行',
    idreq: '通常需输入身份证号/护照号；入场可能核验',
    payment: '信用卡（支持国际卡）、ATM 转账',
    steps: [
      '注册拓元 tixCraft 账号并验证手机',
      '开票时进入系统（可能需排队 + 验证码）',
      '选座、填写证件信息',
      '信用卡付款',
      '电子票通过 App 或邮件取得',
    ],
    tip: '台湾场次验证码多、抢票激烈；建议提前熟悉流程、网速要快。',
  },
};
